### ISSUE TITLE
are the checkpoints released?

### ISSUE THREAD

**Issue by erfanshayegani** [ritzz-ai/GUI-R1#9]
I'm looking for the weights of the models

**Comment by RainBowLuoCS** [comment]
we have released the model weight，please refer to the readme for more details

**Comment by erfanshayegani** [comment]
Thanks for your fast response!

I wen through the Readme, but still cannot find the model weights.

In your evals, you set MODEL_PATH=checkpoints/Qwen2.5-VL-3B-R1-2
but there's no checkpoints/ directory in the repo!

**Comment by RainBowLuoCS** [comment]
in the first line of our readme file，we provide the data ,checkpoint and paper link. just download and use them directly.

**Comment by erfanshayegani** [comment]
Oh, sorry; it turns out for some reason the readme did not render completely for me before. I now can see everything.

Thanks so much!
